apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.43.0/deploy/static/provider/aws/deploy.yaml

